package Vista;

import Controlador.Cliente;
import Controlador.Factura;
import Modelo.ConexionDB;
import Modelo.Producto_Servicio;
import Modelo.Producto_Servicio.Alimentacion;
import Modelo.Producto_Servicio.Educacion;
import Modelo.Producto_Servicio.Salud;
import Modelo.Producto_Servicio.Vestimenta;
import Modelo.Producto_Servicio.Vivienda;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Fac_SuperMaxi extends javax.swing.JFrame {

    private int filaSeleccionada = -1;
    private DefaultTableModel modelotabla;
    private double productos = 0;
    private Factura factura;

    public Fac_SuperMaxi() {
        initComponents();

        modelotabla = (DefaultTableModel) tblClientes.getModel();
        cbxProductos.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtIva.setEnabled(false);
        txtSubTotal.setEnabled(false);
        txtTotal.setEnabled(false);
        btnDeducilesC.setEnabled(false);
        // Este es un ejemplo; usa un valor apropiado

        // Crear una instancia de Factura con los parámetros correctos
    }

    public static boolean validarcedula(String input) {

        if (input.matches("\\d{10}")) {
            int[] A = new int[10];
            int sumpares = 0, sumimpar = 0, s, mul, sumat;

            for (int i = 0; i < 10; i++) {
                A[i] = Character.getNumericValue(input.charAt(i));
            }

            for (int i = 0; i < 9; i += 2) {
                mul = A[i] * 2;
                if (mul > 9) {
                    mul -= 9;
                }
                sumpares += mul;
            }

            for (int i = 1; i < 9; i += 2) {
                sumimpar += A[i];
            }

            sumat = sumpares + sumimpar;
            s = 10 - (sumat % 10);

            if (s == 10) {
                s = 0;
            }

            return s == A[9];
        } else {
            return false;
        }
    }

    public void mostrardatosTabla() {
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double precio = (double) productos * cantidad;
        modelotabla = (DefaultTableModel) tblClientes.getModel();
        modelotabla.addRow(new Object[]{
            txtNombre.getText(),
            txtApellido.getText(),
            txtCedula.getText(),
            txtNumTelefonico.getText(),
            cbxProductos.getSelectedItem(),
            txtCantidad.getText(),
            cbxTipo.getSelectedItem(),
            precio});

        filaSeleccionada = tblClientes.getRowCount() - 1;
    }

    public boolean VerificarDatos() {
        boolean validar = false;

        if (txtNombre.getText().length() >= 3
                && txtApellido.getText().length() >= 3
                && txtCedula.getText().length() == 10
                && txtNumTelefonico.getText().length() == 10
                && cbxTipo.getSelectedItem() != "Seleccione una Opcion"
                && cbxProductos.getSelectedItem() != "Seleccione una opcion"
                && txtCantidad.getText().length() != 0) {

            // Verificar que los campos numéricos sean realmente números
            try {
                Integer.parseInt(txtCedula.getText());
                Integer.parseInt(txtNumTelefonico.getText());
                Integer.parseInt(txtCantidad.getText());
                validar = true;
            } catch (NumberFormatException e) {
                // Si ocurre una excepción, es porque alguno de los campos numéricos no es un número válido
                validar = false;
                JOptionPane.showMessageDialog(null, "Verifique que los campos numéricos sean correctos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        return validar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblNombr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumTelefonico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnDeducilesC = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtMontosCalcular = new javax.swing.JTextField();
        cbxProductos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane5.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        lblNombr.setText("Nombre:");

        jLabel1.setText("Apellido:");

        jLabel2.setText("Numero Telefonico");

        txtNumTelefonico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTelefonicoKeyTyped(evt);
            }
        });

        jLabel3.setText("Correo Electronico");

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        jLabel4.setText("Cedula:");

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Supermaxi-logo.png"))); // NOI18N

        jLabel6.setText("Producto");

        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel7.setText("Tipo Producto");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opcion", "Vivienda", "Educacion", "Vestimenta", "Alimentacion", "Salud" }));
        cbxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxTipoMouseClicked(evt);
            }
        });
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        jLabel8.setText("Cantidad");

        btnProducto.setText("GuardarProducto");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Ruc/Ced", "Telefono", "Producto", "Cantidad", "Tipo Producto", "Precio Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setText("SubTotal");

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        jLabel11.setText("Iva 15%");

        jLabel12.setText("Total");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnDeducilesC.setText("MontosDeducibles");
        btnDeducilesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeducilesCActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        txtMontosCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontosCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDeducilesC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMontosCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnCalcular)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeducilesC)
                    .addComponent(txtMontosCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        cbxProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxProductosMouseClicked(evt);
            }
        });
        cbxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductosActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnProducto)))
                        .addGap(202, 202, 202)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNombr)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtApellido)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNumTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(710, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombr)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumTelefonico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnProducto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        String botones[] = {"Si", "No"};

        if (VerificarDatos()) {
            int numeroTelefono = Integer.parseInt(txtNumTelefonico.getText());
            int cedula = Integer.parseInt(txtCedula.getText());
            int cantidad = Integer.parseInt(txtCantidad.getText());
            String producto_s = cbxProductos.getSelectedItem().toString();
            String tipoProducto = cbxTipo.getSelectedItem().toString();
            String nombreProducto = cbxProductos.getSelectedItem().toString();
            double precio = productos; // Asegúrate de que `producto` esté bien definido

            // Obtener el último ID de factura y generar el siguiente ID
            ConexionDB conexionDB = new ConexionDB();

            Cliente cliente = new Cliente(
                    // Usar el nuevo ID de factura
                    txtNombre.getText(),
                    txtApellido.getText(),
                    cedula,
                    numeroTelefono,
                    producto_s,
                    cantidad,
                    tipoProducto
            );

            int confirmacion = JOptionPane.showOptionDialog(null, "¿Seguro de Guardar Producto?", "Confirmacion", 0, 0, null, botones, this);
            if (confirmacion == JOptionPane.YES_OPTION) {
                mostrardatosTabla();
                (new ConexionDB()).insertarCliente(cliente);
                productos = 0;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cancelado");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Complete todos los campos");
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tblClientes.getModel();

        // Variable para el subtotal
        double subtotal = 0.0;

        // Sumar los valores de la columna 7
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            // Obtener el valor de la columna 7 (precio)
            double precio = (double) modeloTabla.getValueAt(i, 7);

            // Sumar al subtotal
            subtotal += precio;
        }

        double porcentajeIva = 0.15;
        double iva = subtotal * porcentajeIva;
        double total = subtotal + iva;

        // Mostrar los resultados en los campos de texto
        txtSubTotal.setText(String.format("%.2f", subtotal));
        txtIva.setText(String.format("%.2f", iva));
        txtTotal.setText(String.format("%.2f", total));
        btnDeducilesC.setEnabled(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        if (cbxTipo.getSelectedItem().equals("Vivienda")) {
            cbxProductos.removeAllItems();
            cbxProductos.addItem("Seleccione una opcion");
            cbxProductos.addItem("Refrigerador");
            cbxProductos.addItem("Lavadora");
            cbxProductos.addItem("Platos");
            cbxProductos.addItem("Lamparas");
            cbxProductos.addItem("Sabanas");
            cbxProductos.addItem("Toallas");
            cbxProductos.addItem("Cuadros");
            cbxProductos.addItem("Sartenes");
            cbxProductos.setEnabled(true);
            txtCantidad.setEnabled(true);
            txtCantidad.setText("");

        } else if (cbxTipo.getSelectedItem().equals("Educacion")) {
            cbxProductos.removeAllItems();
            cbxProductos.addItem("Seleccione una opcion");
            cbxProductos.addItem("Libros de Lectura");
            cbxProductos.addItem("Enciclopedias");
            cbxProductos.addItem("Pinturas");
            cbxProductos.addItem("Cartucheras");
            cbxProductos.addItem("Calculadora");
            cbxProductos.addItem("Cuadernos");
            cbxProductos.addItem("Esferos");
            cbxProductos.addItem("Hojas A4");
            cbxProductos.addItem("Carpetas");
            cbxProductos.setEnabled(true);
            txtCantidad.setEnabled(true);
            txtCantidad.setText("");

        } else if (cbxTipo.getSelectedItem().equals("Alimentacion")) {
            cbxProductos.removeAllItems();
            cbxProductos.addItem("Seleccione una opcion");
            cbxProductos.addItem("Manzanas");
            cbxProductos.addItem("Zanahorias");
            cbxProductos.addItem("Lechuga");
            cbxProductos.addItem("Pollo");
            cbxProductos.addItem("Carne de res");
            cbxProductos.addItem("Atun");
            cbxProductos.addItem("Leche");
            cbxProductos.addItem("Yogurt");
            cbxProductos.addItem("Queso");
            cbxProductos.addItem("Huevos");
            cbxProductos.addItem("Arroz");
            cbxProductos.addItem("Avena");
            cbxProductos.addItem("Pan");
            cbxProductos.addItem("Cafe");
            cbxProductos.addItem("Te");
            cbxProductos.addItem("Pimienta");
            cbxProductos.setEnabled(true);
            txtCantidad.setEnabled(true);
            txtCantidad.setText("");

        } else if (cbxTipo.getSelectedItem().equals("Vestimenta")) {
            cbxProductos.removeAllItems();
            cbxProductos.addItem("Seleccione una opcion");
            cbxProductos.addItem("Camisetas");
            cbxProductos.addItem("Pantalones");
            cbxProductos.addItem("Corbatas");
            cbxProductos.addItem("Gorras");
            cbxProductos.addItem("Vestidos");
            cbxProductos.addItem("Correas");
            cbxProductos.addItem("Zapatos");
            cbxProductos.setEnabled(true);
            txtCantidad.setEnabled(true);
            txtCantidad.setText("");

        } else if (cbxTipo.getSelectedItem().equals("Salud")) {
            cbxProductos.removeAllItems();
            cbxProductos.addItem("Seleccione una opcion");
            cbxProductos.addItem("Cepillos de Dientes");
            cbxProductos.addItem("Vitaminas");
            cbxProductos.addItem("Protector Solar");
            cbxProductos.addItem("Analgesicos");
            cbxProductos.addItem("Jarabes");
            cbxProductos.addItem("Vendas");
            cbxProductos.addItem("Curitas");
            cbxProductos.addItem("Paracetamol");
            cbxProductos.setEnabled(true);
            txtCantidad.setEnabled(true);
            txtCantidad.setText("");

        } else if (cbxTipo.getSelectedItem().equals("Seleccione una Opcion")) {
            cbxProductos.removeAllItems();
            cbxProductos.setEnabled(false);
            txtCantidad.setEnabled(false);
            txtCantidad.setText("");
        }
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char validacioncedula = evt.getKeyChar();
        if (Character.isLetter(validacioncedula)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNumTelefonicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelefonicoKeyTyped
        char validacionnumerotelefono = evt.getKeyChar();
        if (Character.isLetter(validacionnumerotelefono)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNumTelefonicoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validacionnombre = evt.getKeyChar();
        if (Character.isDigit(validacionnombre)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo caracteres", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char validacionapellido = evt.getKeyChar();
        if (Character.isDigit(validacionapellido)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo caracteres", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        String input = txtCorreo.getText().trim();
        String[] palabras = input.split("\\s+");
        if (palabras.length <= 35 && input.matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {

        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese una dirección de correo electrónico válida con un límite de 35 palabras", "Error", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        String input = txtCedula.getText();
        if (input.matches("\\d*")) {
            if (txtCedula.getText().length() == 10) {
                if (validarcedula(input)) {

                } else {
                    JOptionPane.showMessageDialog(this, "Por favor ingrese una cedula valida", "Error", JOptionPane.ERROR_MESSAGE);
                    txtCedula.setText(" ");
                    txtCedula.requestFocus();
                }
            } else if (txtCedula.getText().length() > 10) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese cedula valida, solo 10 digitos", "Error", JOptionPane.ERROR_MESSAGE);
                txtCedula.setText(" ");
                txtCedula.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese al menos 10 digitos para cedula", "Error", JOptionPane.ERROR_MESSAGE);
                txtCedula.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String input = txtNombre.getText().trim();
        if (input.length() >= 3) {

        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese al menos 3 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        String input = txtApellido.getText().trim();
        if (input.length() >= 3) {

        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese al menos 3 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            txtApellido.requestFocus();
        }
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char validacioncantidad = evt.getKeyChar();
        if (Character.isLetter(validacioncantidad)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (Character.isDigit(validacioncantidad)) {
            // Obtener el texto actual del campo de texto
            String input = txtCantidad.getText().trim();

            // Concatenar el nuevo carácter al texto actual
            String nuevoInput = input + validacioncantidad;

            // Verificar si el número está en el rango de 1 a 100
            int numero;
            try {
                numero = Integer.parseInt(nuevoInput);
            } catch (NumberFormatException e) {
                // Si no se puede convertir a número, entonces el input no es válido
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(this, "Ingresar solo números entre 1 y 100", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (numero < 1 || numero > 100) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(this, "Ingresar solo números entre 1 y 100", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Si no es un dígito, consumir el evento
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo números entre 1 y 100", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        String input = txtCantidad.getText().trim();
        if (input.length() > 0) {

        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese cantidades reales", "Error", JOptionPane.ERROR_MESSAGE);
            txtCantidad.requestFocus();
        }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void cbxProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxProductosMouseClicked
        txtCantidad.setText("");
    }//GEN-LAST:event_cbxProductosMouseClicked

    private void cbxTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoMouseClicked
        txtCantidad.setText("");
    }//GEN-LAST:event_cbxTipoMouseClicked

    private void cbxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductosActionPerformed
        if (cbxProductos.getSelectedItem().equals("Refrigerador")) {
            productos = 1200.00;
        } else if (cbxProductos.getSelectedItem().equals("Lavadora")) {
            productos = 900.00;
        } else if (cbxProductos.getSelectedItem().equals("Platos")) {
            productos = 5.00;
        } else if (cbxProductos.getSelectedItem().equals("Lamparas")) {
            productos = 25.00;
        } else if (cbxProductos.getSelectedItem().equals("Sabanas")) {
            productos = 20.00;
        } else if (cbxProductos.getSelectedItem().equals("Toallas")) {
            productos = 15.00;
        } else if (cbxProductos.getSelectedItem().equals("Cuadros")) {
            productos = 50.00;
        } else if (cbxProductos.getSelectedItem().equals("Sartenes")) {
            productos = 35.00;
        } else if (cbxProductos.getSelectedItem().equals("Libros de Lectura")) {
            productos = 20.00;
        } else if (cbxProductos.getSelectedItem().equals("Enciclopedias")) {
            productos = 50.00;
        } else if (cbxProductos.getSelectedItem().equals("Pinturas")) {
            productos = 2.00;
        } else if (cbxProductos.getSelectedItem().equals("Cartucheras")) {
            productos = 4.00;
        } else if (cbxProductos.getSelectedItem().equals("Calculadora")) {
            productos = 18.00;
        } else if (cbxProductos.getSelectedItem().equals("Cuadernos")) {
            productos = 1.20;
        } else if (cbxProductos.getSelectedItem().equals("Esferos")) {
            productos = 0.80;
        } else if (cbxProductos.getSelectedItem().equals("Hojas A4")) {
            productos = 0.60;
        } else if (cbxProductos.getSelectedItem().equals("Carpetas")) {
            productos = 4.00;
        } else if (cbxProductos.getSelectedItem().equals("Manzanas")) {
            productos = 1.50;
        } else if (cbxProductos.getSelectedItem().equals("Zanahorias")) {
            productos = 0.80;
        } else if (cbxProductos.getSelectedItem().equals("Lechuga")) {
            productos = 1.00;
        } else if (cbxProductos.getSelectedItem().equals("Pollo")) {
            productos = 1.75;
        } else if (cbxProductos.getSelectedItem().equals("Carne de res")) {
            productos = 3.25;
        } else if (cbxProductos.getSelectedItem().equals("Atun")) {
            productos = 1.25;
        } else if (cbxProductos.getSelectedItem().equals("Leche")) {
            productos = 1.20;
        } else if (cbxProductos.getSelectedItem().equals("Yogurt")) {
            productos = 1.50;
        } else if (cbxProductos.getSelectedItem().equals("Queso")) {
            productos = 3.00;
        } else if (cbxProductos.getSelectedItem().equals("Huevos")) {
            productos = 2.00;
        } else if (cbxProductos.getSelectedItem().equals("Arroz")) {
            productos = 1.00;
        } else if (cbxProductos.getSelectedItem().equals("Avena")) {
            productos = 1.50;
        } else if (cbxProductos.getSelectedItem().equals("Pan")) {
            productos = 0.10;
        } else if (cbxProductos.getSelectedItem().equals("Cafe")) {
            productos = 5.00;
        } else if (cbxProductos.getSelectedItem().equals("Te")) {
            productos = 2.50;
        } else if (cbxProductos.getSelectedItem().equals("Pimienta")) {
            productos = 0.20;
        } else if (cbxProductos.getSelectedItem().equals("Camisetas")) {
            productos = 15.00;
        } else if (cbxProductos.getSelectedItem().equals("Pantalones")) {
            productos = 30.00;
        } else if (cbxProductos.getSelectedItem().equals("Corbatas")) {
            productos = 5.00;
        } else if (cbxProductos.getSelectedItem().equals("Gorras")) {
            productos = 20.00;
        } else if (cbxProductos.getSelectedItem().equals("Vestidos")) {
            productos = 25.00;
        } else if (cbxProductos.getSelectedItem().equals("Correas")) {
            productos = 15.00;
        } else if (cbxProductos.getSelectedItem().equals("Zapatos")) {
            productos = 30.00;
        } else if (cbxProductos.getSelectedItem().equals("Cepillos de Dientes")) {
            productos = 2.00;
        } else if (cbxProductos.getSelectedItem().equals("Vitaminas")) {
            productos = 10.00;
        } else if (cbxProductos.getSelectedItem().equals("Protector Solar")) {
            productos = 8.00;
        } else if (cbxProductos.getSelectedItem().equals("Analgesicos")) {
            productos = 5.00;
        } else if (cbxProductos.getSelectedItem().equals("Jarabes")) {
            productos = 7.00;
        } else if (cbxProductos.getSelectedItem().equals("Vendas")) {
            productos = 1.50;
        } else if (cbxProductos.getSelectedItem().equals("Curitas")) {
            productos = 0.10;
        } else if (cbxProductos.getSelectedItem().equals("Paracetamol")) {
            productos = 1.00;
        }

    }//GEN-LAST:event_cbxProductosActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        MostrarFacturas monto = new MostrarFacturas();
        monto.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDeducilesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeducilesCActionPerformed
       Factura factura = new Factura();
    DefaultTableModel modeloTabla = (DefaultTableModel) tblClientes.getModel();

    // Añadir productos a la factura desde la tabla
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        String nombreProducto = (String) modeloTabla.getValueAt(i, 0);
        double precio = Double.parseDouble(modeloTabla.getValueAt(i, 7).toString());
        int cantidad = Integer.parseInt(modeloTabla.getValueAt(i, 5).toString());
        String categoria = (String) modeloTabla.getValueAt(i, 6);
        
        Producto_Servicio producto;
        switch (categoria) {
            case "Vivienda":
                producto = new Vivienda(nombreProducto, precio, cantidad);
                break;
            case "Salud":
                producto = new Salud(nombreProducto, precio, cantidad);
                break;
            case "Alimentacion":
                producto = new Alimentacion(nombreProducto, precio, cantidad);
                break;
            case "Vestimenta":
                producto = new Vestimenta(nombreProducto, precio, cantidad);
                break;
            case "Educacion":
                producto = new Educacion(nombreProducto, precio, cantidad);
                break;
            default:
                throw new IllegalArgumentException("Categoría desconocida: " + categoria);
        }
        
        factura.agregarProducto(producto);
    }

    // Calcular los deducibles
    ArrayList<Double> deducibles = factura.calcularDeducibles();

    // Mostrar los deducibles en el campo de texto
    double totalDeducibles = 0.0;
    for (double deducible : deducibles) {
        totalDeducibles += deducible;
    }
    txtMontosCalcular.setText(String.format("%.2f", totalDeducibles));
    }//GEN-LAST:event_btnDeducilesCActionPerformed

    private void txtMontosCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontosCalcularActionPerformed

    }//GEN-LAST:event_txtMontosCalcularActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fac_SuperMaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fac_SuperMaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fac_SuperMaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fac_SuperMaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fac_SuperMaxi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDeducilesC;
    private javax.swing.JButton btnProducto;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNombr;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtMontosCalcular;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumTelefonico;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
